#!/bin/bash

IFS='
'

VCFTOOLS=$1
VCFCONCAT=$2
TEMP=$3
UNAME=$4
OUTPUT=$5
EDITSITE=$6

cd $TEMP
for f in $TEMP/*.recode.vcf; do
	bgzip -c $f > $f.gz
	tabix -p vcf $f.gz
done
if [ -f $TEMP/temp.vcf.gz ]; then
	rm $TEMP/temp.vcf.gz
fi

ls $TEMP/*.recode.vcf.gz > lsfile

$VCFCONCAT -f lsfile | bgzip -c > $TEMP/temp.vcf.gz
$VCFTOOLS --gzvcf $TEMP/temp.vcf.gz --exclude-positions $EDITSITE --recode --recode-INFO-all --out $TEMP/$UNAME

#bgzip -c $UNAME.recode.vcf > $UNAME.recode.vcf.gz
#tabix -p vcf $UNAME.recode.vcf.gz
#mv $TEMP/$UNAME.recode.vcf $OUTPUT
